# auto-push-branch.ps1 - Auto-commit and push to a new branch
# Creates a timestamped branch, commits, and pushes

param(
    [string]$Message = "Auto-update",
    [string]$BranchPrefix = "auto"
)

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $ProjectRoot

Write-Host "=== Auto-Push to New Branch ===" -ForegroundColor Cyan

# Check for changes
$status = git status --porcelain
if (-not $status) {
    Write-Host "No changes to commit." -ForegroundColor Yellow
    exit 0
}

# Create branch name with timestamp
$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$branchName = "$BranchPrefix/$timestamp"

Write-Host "Creating branch: $branchName" -ForegroundColor Green

# Create and switch to new branch
git checkout -b $branchName

# Stage all changes
git add .

# Commit
$fullMessage = @"
$Message

Branch: $branchName
Timestamp: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

🤖 Auto-committed by Conductor Bridge
"@

git commit -m $fullMessage

# Push to remote
Write-Host "Pushing to origin/$branchName..." -ForegroundColor Cyan
git push -u origin $branchName

if ($LASTEXITCODE -eq 0) {
    Write-Host "`n✓ Successfully pushed to: $branchName" -ForegroundColor Green

    # Create PR suggestion
    Write-Host "`nTo create a Pull Request, run:" -ForegroundColor Yellow
    Write-Host "gh pr create --title `"$Message`" --body `"Auto-generated by Conductor Bridge`"" -ForegroundColor White
} else {
    Write-Host "Push failed!" -ForegroundColor Red
}

# Switch back to main/master
$defaultBranch = git symbolic-ref refs/remotes/origin/HEAD 2>$null
if ($defaultBranch) {
    $defaultBranch = $defaultBranch -replace "refs/remotes/origin/", ""
} else {
    $defaultBranch = "master"
}
git checkout $defaultBranch

Write-Host "`nBack on branch: $defaultBranch" -ForegroundColor Cyan
